import test from 'node:test';
import assert from 'node:assert/strict';
import {compareDesync,compareDiagnostics,caseMarkdown} from '../../.artifacts/desync.mjs';
const command=(index,frame,source=3)=>({index,frame,source_index:source,message_type:582,name:'MSG_MOVETO',argument_sha256:String(index),arguments:[]});
function report(){return {file:{name:'test.KWReplay',sha256:'a'},match:{game_session_id:7,map_id:'m',map_crc:4,seed:42},players:[{source_index:3,name:'A'},{source_index:4,name:'B'}],commands:{items:[command(0,20),command(1,30),command(2,40)]},desync:{title:'Recorded states disagree',incidents:[],checkpoints:[{epoch:0,frame:450,reports:[{source_index:3,crc:1,playback:false},{source_index:4,crc:2,playback:false}]}]}};}
test('missing command resynchronizes instead of cascading',()=>{const a=report(),b=report();b.commands.items.splice(1,1);const c=compareDesync(a,b);assert.equal(c.differenceCount,1);assert.equal(c.firstDifference.frame,30);assert.equal(c.firstDifference.kind,'Only in A');});
test('source remapping by unique names preserves comparison',()=>{const a=report(),b=report();b.players[0].source_index=8;b.commands.items.forEach(c=>c.source_index=8);b.desync.checkpoints[0].reports[0].source_index=8;const c=compareDesync(a,b);assert.equal(c.differenceCount,0);assert.equal(c.crcDifferences.length,0);assert.equal(c.unknownSource,false);});
test('swapped player CRCs cannot hide behind equal CRC sets',()=>{const a=report(),b=report();b.desync.checkpoints[0].reports.reverse();b.desync.checkpoints[0].reports.forEach((r,i)=>r.source_index=i+3);assert.equal(compareDesync(a,b).crcDifferences.length,2);});
test('CRC epoch, mode and missing reports remain distinct',()=>{for(const edit of [b=>b.desync.checkpoints[0].epoch++,b=>b.desync.checkpoints[0].reports[0].playback=true,b=>b.desync.checkpoints=[]]){const b=report();edit(b);assert.ok(compareDesync(report(),b).crcDifferences.length);}});
test('duplicate names force provisional source comparisons',()=>{const a=report(),b=report();a.players[1].name='A';assert.equal(compareDesync(a,b).unknownSource,true);});
test('missing or conflicting metadata cannot match identity',()=>{for(const edit of [b=>b.match.seed++,b=>delete b.match.map_crc,b=>b.match.game_session_id=0]){const b=report();edit(b);assert.equal(compareDesync(report(),b).sameSession,false);}});
test('global interleaving is visible even when player lanes match',()=>{const a=report(),b=report();a.commands.items=[command(0,20,3),command(1,20,4)];b.commands.items=[...a.commands.items].reverse();const c=compareDesync(a,b);assert.equal(c.differenceCount,0);assert.equal(c.orderDiffers,true);});
test('opaque argument hash differences are preserved',()=>{const a=report(),b=report();b.commands.items[0].argument_sha256='changed';assert.equal(compareDesync(a,b).firstDifference.kind,'Changed');});
const diagnostic=()=>({name:'a.bin',sha256:'abc',kind:'binary',frame:900,format_version:1,complete:true,forced:false,settings:{},fields:[{path:'Object 204[1]/Health[1]',type:'real',value:0,value_sha256:'positive-zero'}]});
test('exact bytes catch float-bit differences and missing fields',()=>{const a=diagnostic(),b=diagnostic();b.fields[0].value_sha256='negative-zero';assert.equal(compareDiagnostics(a,b).total,1);b.fields=[];assert.equal(compareDiagnostics(a,b).differences[0].right,null);});
test('capture comparison explains frame, settings and partial limits',()=>{const a=diagnostic(),b=diagnostic();b.frame=901;b.complete=false;b.forced=true;b.settings.deepCRC=true;const c=compareDiagnostics(a,b);assert.equal(c.warnings.length,4);assert.equal(c.settings[0].setting,'deepCRC');});
test('case notes carry hashes and escape supplied names',()=>{const r=report();r.file.name='<script>\n# injected';r.desync_case={peers:[],diagnostics:[],notes:'Checked object 204.'};const s=caseMarkdown(r);assert.ok(s.includes('SHA-256: a'));assert.ok(s.includes('Checked object 204.'));assert.ok(!s.includes('<script>'));});
