import {escapeHtml as e, display, timeLabel} from './analytics';
import {compareDesync,compareDiagnostics} from './desync';
import type {ReplayReport,DiagnosticField} from './types';

const button=(name:string,action:string,extra='')=>`<button class="button" data-action="${action}" ${extra}>${e(name)}</button>`;
const card=(title:string,body:string)=>`<section class="card"><h2>${e(title)}</h2><div class="desync-body">${body}</div></section>`;
const table=(heads:string[],rows:string[])=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${heads.length}">No differences in the decoded data.</td></tr>`}</tbody></table></div>`;
const input=(title:string,id:string,accept:string)=>`<label class="button">${e(title)}<input class="file-overlay" id="${id}" data-upload type="file" multiple accept="${accept}" aria-label="${e(title)}"></label>`;
const value=(f:DiagnosticField|null)=>f?`${e(display(f.value))}<small>${f.offset!=null?'Byte 0x'+f.offset.toString(16):'Line '+f.line}</small>`:'Missing';

export function renderDesync(r:ReplayReport,offline:boolean,incidentIndex:number,checkpointKey:string,diagnosticA:number,diagnosticB:number,query:string){
 const d=r.desync;
 if(!d)return card('Desync Lab','<p>This older report has no Desync Lab results. Analyze the original replay with the current app.</p>');
 const incident=d.incidents[incidentIndex]??d.incidents[0],coverage=d.coverage;
 const current=d.checkpoints.find(p=>`${p.epoch}:${p.frame}`===checkpointKey)??d.checkpoints.find(p=>p.frame===incident?.frame&&p.epoch===incident?.epoch)??d.checkpoints.at(-1);
 const c=r.desync_case??{peers:[],diagnostics:[],notes:''};
 const captureA=c.diagnostics[diagnosticA]??c.diagnostics[0],captureB=c.diagnostics[diagnosticB]??c.diagnostics[1];
 const captureDiff=captureA&&captureB?compareDiagnostics(captureA,captureB):null;
 const firstField=captureDiff?.differences[0];
 const issueCount=coverage.decode_errors+coverage.invalid_crc_count+coverage.conflicting_count+Number(coverage.mixed_mode_count??0);
 let html=`<section class="card desync-summary ${d.status==='disagreement'?'desync-danger':''}"><p class="eyebrow">DESYNC LAB / 1.02</p><h2>${e(d.title)}</h2><p>${incident?`First recorded incident: frame ${d.incidents[0].frame} (${timeLabel(d.incidents[0].frame)}). Start with the checkpoint window below.`:'No disagreement is established by the available reports. Missing checks and equal checksums cannot rule out a desync.'}</p><div class="row-actions">${incident?button('Inspect this window','desync-window','data-view="Commands"'):''}${button('Export case notes','desync-export')}${!offline?button('Export case HTML','html'):''}</div></section>`;
 if(firstField)html+=card('First differing captured field',`<h3>${e(firstField.path)}</h3><p>${e(display(firstField.left?.value??'Missing'))} / ${e(display(firstField.right?.value??'Missing'))}</p><p>${captureDiff!.warnings.length?'Check capture compatibility before following this field. '+e(captureDiff!.warnings.join(' ')):'Start with this captured object or module, then inspect its preceding updates. Capture order does not establish which field diverged first in time.'}</p><p class="note">${e(captureA.name)} compared with ${e(captureB.name)}. Replay association is user supplied.</p>`);
 html+=`<div class="metrics">${[['Checkpoints',coverage.checkpoint_count],['Differing',coverage.disagreement_count],['Incomplete',coverage.incomplete_count],['Data issues',issueCount]].map(([label,n])=>`<div class="metric"><small>${label}</small><strong>${n}</strong></div>`).join('')}</div>`;
 html+=card('Where to look first',`<ol class="next-steps"><li><strong>${incident?'Inspect the recorded window':'Add more evidence'}</strong><p>${incident?`Frames ${incident.start_frame}-${incident.frame}, with ${incident.command_count} action commands. ${incident.last_matching_frame==null?'No earlier matching checkpoint covers these sources.':`The last matching checkpoint for these sources is ${incident.last_matching_frame}.`} This is an investigation window, not the exact fault time.`:'Add another player\'s recording or native diagnostic files below.'}</p></li><li><strong>Compare player recordings</strong><p>Look for command differences before the first CRC disagreement. Matching commands can still produce different simulation states.</p></li><li><strong>Compare captured fields</strong><p>Native text or binary dumps can identify the first differing field. Check capture frames and diagnostic settings first.</p></li></ol>`);
 if(incident){
  html+=card('Investigation window',`<div class="filters"><label>Incident<select id="desync-incident">${d.incidents.map((x,i)=>`<option value="${i}" ${i===incidentIndex?'selected':''}>Frame ${x.frame}, epoch ${x.epoch}: ${e(x.kind.replaceAll('_',' '))}</option>`).join('')}</select></label>${button('Show commands','desync-window','data-view="Commands"')}${button('Show camera','desync-window','data-view="Camera"')}</div><p>${e(Object.entries(incident.categories).map(([n,c])=>`${c} ${n.toLowerCase()}`).join(' / ')||'No action commands in this interval.')}</p><div class="row-actions">${incident.objects.slice(0,12).map(o=>button(`Object ${o.id} (${o.references})`,'desync-object',`data-id="${o.id}"`)).join('')}</div><p class="note">Object references show context, not evidence that the object caused the desync.</p>${table(['Frame','Player','Recorded command','Inspect'],incident.command_indices.slice(0,20).map(i=>{const x=r.commands.items[i];return `<tr><td>${x.frame}</td><td>${e(x.player)}</td><td>${e(x.display_name??x.name)}</td><td>${button('Inspect','inspect',`data-index="${i}"`)}</td></tr>`}))}<p class="note">Showing up to 20 actions. Show commands to inspect the full window, including selection and control messages.</p>`);
 }
 const statuses:Record<string,string>={matching_reports:'Matching',disagreement:'Different',insufficient_reports:'Insufficient',conflicting_reports:'Conflicting',mixed_modes:'Mixed modes'};
 html+=card('Checkpoint evidence',`<p>Select a checkpoint to see each player\'s value and when it was recorded. Duplicate reports never count as extra players.</p><div class="checkpoint-strip">${d.checkpoints.slice(0,2000).map(p=>`<button class="checkpoint ${p.status}" data-action="desync-checkpoint" data-key="${p.epoch}:${p.frame}" ${p===current?'aria-pressed="true"':'aria-pressed="false"'}>${p.frame}<small>${statuses[p.status]??p.status}</small></button>`).join('')||'<p>No usable CRC commands in this file.</p>'}</div>${d.checkpoints.length>2000?'<p>Showing the first 2,000 checkpoints; JSON retains every checkpoint.</p>':''}${current?`<h3>Frame ${current.frame}, epoch ${current.epoch}</h3><p>${statuses[current.status]}. ${current.missing_sources.length?`Missing initial-roster sources: ${current.missing_sources.join(', ')}. Player membership may have changed.`:''} ${current.duplicate_reports} duplicate report(s).</p>${table(['Player / source','CRC','Recorded frame','Delay','Mode','Flag','Inspect'],current.reports.map(x=>`<tr><td>${e(x.player)} / ${x.source_index}</td><td class="mono">0x${x.crc.toString(16).padStart(8,'0')}</td><td>${x.record_frame}</td><td>${x.delay_frames} frames</td><td>${x.playback?'Playback':'Live'}</td><td>${x.mismatch_reporting?'Set':'Not set'}</td><td>${button('Inspect CRC','inspect',`data-index="${x.command_index}"`)}</td></tr>`))}`:''}`);
 html+=card('Compare player recordings',`<p>Add up to three recordings. Match identity uses session, map, map CRC and seed. Player names map source numbers only when unique in both rosters.</p>${!offline?input('Add player replays','desync-peers','.KWReplay,.kwreplay'):''}${!offline?button('Use comparison replay','desync-use-comparison'):''}${c.peers.map((peer,i)=>{
  const x=compareDesync(r,peer),first=x.firstDifference;
  return `<article class="coverage"><h3>${e(peer.file.name)}</h3><p class="notice">${x.sameSession?'Session metadata matches; file origin is unverified.':`Different or unconfirmed match. ${x.conflicts.length?'Conflicting fields: '+e(x.conflicts.join(', ')):''} Differences cannot establish a shared desync.`}</p>${x.unknownSource?'<p>Some sources could not be mapped by unique player names. Source-number comparisons are provisional.</p>':''}<p>${x.differenceCount} command difference(s); ${x.crcDifferences.length} player/checkpoint difference(s). ${x.orderDiffers&&!x.differenceCount?'Global order differs, but each player\'s filtered command sequence matches.':''}</p>${first?`<p>First retained command difference: frame ${first.frame}${incident?first.frame<=incident.frame?' (at or before this incident).':' (after this incident).':'.'}</p>`:''}${table(['Frame','Player','Difference','A','B'],x.differences.slice(0,15).map(z=>`<tr><td>${z.frame}</td><td>${e(z.player)}</td><td>${e(z.kind)}</td><td>${z.left?button(z.left.display_name??z.left.name,'inspect',`data-index="${z.left.index}"`):'Missing'}</td><td>${z.right?button(z.right.display_name??z.right.name,'desync-peer-command',`data-peer="${i}" data-index="${z.right.index}"`):'Missing'}</td></tr>`))}<details><summary>CRC differences by player</summary>${table(['Frame / epoch','Player','A','B'],x.crcDifferences.slice(0,100).map(z=>`<tr><td>${z.frame} / ${z.epoch}</td><td>${e(z.player)}</td><td>${e(z.left.join(', ')||'Missing')}</td><td>${e(z.right.join(', ')||'Missing')}</td></tr>`))}</details><p class="note">${e(x.alignment)} Showing up to 15 command differences.</p>${!offline?button('Remove recording','desync-remove-peer',`data-peer="${i}"`):''}</article>`;
 }).join('')}`);
 html+=card('Native diagnostic files',`<p>Add DESYNC text reports or tagged BIN_DESYNC captures from KW 1.02. These files may contain player names and machine details; exports retain decoded content.</p>${!offline?input('Add diagnostic files','desync-diagnostics','.txt,.bin'):''}${c.diagnostics.map((doc,i)=>`<article class="coverage"><strong>${e(doc.name)}</strong><p>${doc.fields.length} fields / frame ${doc.frame??'unknown'} / ${doc.complete?'decoded':'partial or unsupported'}${doc.forced?' / intentionally forced diagnostic':''}</p>${doc.issues.map(x=>`<p class="notice error">${e(x)}</p>`).join('')}${!offline?button('Remove capture','desync-remove-diagnostic',`data-index="${i}"`):''}</article>`).join('')}<p class="note">Captured fields are evidence from the supplied files. Their connection to this replay is not verified automatically.</p>`);
 if(c.diagnostics.length>=2){
  const a=c.diagnostics[diagnosticA]??c.diagnostics[0],b=c.diagnostics[diagnosticB]??c.diagnostics[1],x=compareDiagnostics(a,b);
  const choices=(selected:number)=>c.diagnostics.map((doc,i)=>`<option value="${i}" ${i===selected?'selected':''}>${e(doc.name)}</option>`).join('');
  const matches=x.differences.filter(z=>`${z.path} ${display(z.left?.value)} ${display(z.right?.value)}`.toLowerCase().includes(query.toLowerCase()));
  html+=card('Captured field differences',`<div class="filters"><label>Capture A<select id="diagnostic-a">${choices(diagnosticA)}</select></label><label>Capture B<select id="diagnostic-b">${choices(diagnosticB)}</select></label><label class="search">Find a field<input id="diagnostic-search" type="search" value="${e(query)}" placeholder="Object, module, field or value"></label></div>${x.warnings.map(w=>`<p class="notice">${e(w)}</p>`).join('')}<p>${x.total} differing or missing fields. ${x.differences[0]?`Start at ${e(x.differences[0].path)}.`:''}</p><p class="note">Binary comparison uses exact value bytes, including float bits. Paths follow captured block names and occurrences. A field difference narrows the investigation; it does not identify the code that first caused it.</p>${table(['Captured field','A','B'],matches.slice(0,100).map(z=>`<tr><td>${e(z.path)}</td><td>${value(z.left)}</td><td>${value(z.right)}</td></tr>`))}<p class="note">Showing up to 100 matches from the first 1,000 differences. Export JSON retains each capture\'s decoded fields.</p><details><summary>Diagnostic settings</summary>${table(['Setting','A','B'],x.settings.map(z=>`<tr><td>${e(z.setting)}</td><td>${e(display(z.left))}</td><td>${e(display(z.right))}</td></tr>`))}</details>`);
 }
 html+=card('Investigation notes',`<label>What you checked<textarea id="desync-notes" rows="4" maxlength="10000" placeholder="Reproduction steps, changed files, findings...">${e(c.notes)}</textarea></label><div class="row-actions">${button('Export case notes','desync-export')}${!offline?button('Save case in library','save')+button('Export case HTML','html'):''}</div><p class="note">Case JSON and HTML include added recordings, decoded diagnostics and these notes. Raw replay and diagnostic bytes are excluded.</p>`);
 return html;
}
